app:
  image: node:12-alpine
  command: sh -c "yarn install && yarn dev"
  environment:
    - PORT
    - FIREBASE_AUTH_PROVIDER_X509_CERT_URL
    - FIREBASE_AUTH_URI
    - FIREBASE_CLIENT_EMAIL
    - FIREBASE_CLIENT_ID
    - FIREBASE_CLIENT_X509_CERT_URL
    - FIREBASE_PROJECT_ID
    - FIREBASE_PRIVATE_KEY_ID
    - FIREBASE_PRIVATE_KEY
    - FIREBASE_TOKEN_URI
    - FIREBASE_TYPE
    - MAIL_DESTINATION
    - SENDGRID_API_KEY
    - TMDB_API_URL
    - TMDB_API_KEY
    - TWILIO_AUTH_TOKEN
    - TWILIO_PHONE_NUMBER
    - TWILIO_SID
  ports:
    - "3001:3001"
    - "9229:9229"
  volumes:
    - .:/app
  working_dir: /app
